version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        update-types: [major, minor]
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        update-types: [major, minor]
